name: BUEnchant
main: com.github.blockedup.buenchant.buenchant
version: 1.0
author: zDylann
permissions:
  bue.admin:
    description: AntiEnchant full permission.
    default: op
commands:
  bue_reload:
    description: Reload the plugin.
    usage: /ae_reload
    permission: ae.admin
    permission-message: You don't have permission to do that.
