name: BUEnchant
main: com.github.blockedup.buenchant
version: 1.0
author: zDylann
permissions:
  bue.admin:
    description: AntiEnchant full permission.
    default: op
  bue.enchant:
    description: Enchanting permission.
    default: op
  bue.unenchant:
    description: Unenchant permission.
    default: op
commands:
  bue_reload:
    description: Reload the plugin.
    usage: /ae_reload
    permission: ae.admin
    permission-message: You don't have permission to do that.
  bue_unenchant:
    description: Unenchant item that you are currently holding.
    usage: /ae_unenchant
    permission: ae.unenchant
    permission-message: You don't have permission to do that.
    
